spring:
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:mydb.sqlite
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083
          jwk-set-uri: http://localhost:8083/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: FoodityKeycloak
  resource: login-app
  public-client: true
  security-constraints:
    - authRoles:
        - regular
      securityCollections:
        - patterns:
            - /users/*



