spring:

  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:mydb.sqlite
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: FoodityKeycloak
  resource: login-app
  public-client: true
  credentials:
    secret: 82ccfbb6-26d2-45a4-a202-24c8d09f90af
  security-constraints[0]:
    authRoles:
      - regular
    securityCollections[0]:
      patterns: /profiles

file:
  upload-dir: /uploads