spring:

  http:
    converters:
      preferred-json-mapper: gson

  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:mydb.sqlite
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083
          jwk-set-uri: http://localhost:8083/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: FoodityKeycloak
  resource: login-app
  credentials:
    secret: 82ccfbb6-26d2-45a4-a202-24c8d09f90af